apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-oss-pvc
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      alicloud-pvname: grafana-oss-pv