name: 'etcd-service-01'
data-dir: /data/applications/data/etcd-data
# wal-dir: /data/applications/data/etcd-data/wal
snapshot-count: 5000
heartbeat-interval: 100
election-timeout: 1000
quota-backend-bytes: 8589934592
max-request-bytes: 10485760
listen-peer-urls: 'https://172.16.100.61:2380'
listen-client-urls: 'https://172.16.100.61:2379,http://127.0.0.1:2379'
max-snapshots: 3
max-wals: 5
cors:
initial-advertise-peer-urls: 'https://172.16.100.61:2380'
advertise-client-urls: 'https://172.16.100.61:2379'
discovery:
discovery-fallback: 'proxy'
discovery-proxy:
discovery-srv:
initial-cluster: 'etcd-service-01=https://172.16.100.61:2380,etcd-service-02=https://172.16.100.62:2380,etcd-service-03=https://172.16.100.63:2380'
initial-cluster-token: 'etcd-opsk8s-cluster'
initial-cluster-state: 'new'
strict-reconfig-check: false
enable-v2: true
enable-pprof: true
proxy: 'off'
proxy-failure-wait: 5000
proxy-refresh-interval: 30000
proxy-dial-timeout: 1000
proxy-write-timeout: 5000
proxy-read-timeout: 0
client-transport-security:
  cert-file: '/data/applications/etcd-service/certs/etcd-server-keys.pem'
  key-file: '/data/applications/etcd-service/certs/etcd-server-keys-key.pem'
  client-cert-auth: true
  trusted-ca-file: '/data/applications/etcd-service/certs/etcd-service-ca.pem'
  auto-tls: true
peer-transport-security:
  cert-file: '/data/applications/etcd-service/certs/etcd-server-keys.pem'
  key-file: '/data/applications/etcd-service/certs/etcd-server-keys-key.pem'
  peer-client-cert-auth: true
  trusted-ca-file: '/data/applications/etcd-service/certs/etcd-service-ca.pem'
  auto-tls: true
debug: false
log-package-levels:
log-outputs: [stdout]
force-new-cluster: false