apiVersion: v1
kind: Service
metadata:
  name: devops-redis-service
  namespace: devops
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
  selector:
    app: redis