kind: ConfigMap
apiVersion: v1
metadata:
  name: devops-redis-cm
  namespace: devops
  labels:
    app: redis
data:
  redis.conf: |-
    dir /data
    port 6379
    bind 0.0.0.0
    appendonly yes
    protected-mode no
    requirepass devops
    pidfile /data/redis-6379.pid