apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-mysql-deployment
  namespace: devops
  labels:
    app: devops-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: registry.cn-chengdu.aliyuncs.com/ops-k8s/mysql:5.7.21
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              subPath: "mysql"
              name: mysql-data
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: devops-mysql-secrets
                  key: ROOT_PASSWORD
      volumes:
        - name: mysql-data
          hostPath:
            path: /data/applications/data
      nodeSelector:
        mysql-server: "true"